# Generated by Django 4.2.8 on 2023-12-29 13:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='blog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cook_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Время на приготовление'),
        ),
        migrations.AlterField(
            model_name='post',
            name='directions',
            field=ckeditor.fields.RichTextField(verbose_name='Действия'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='articles/', verbose_name='Изображение поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=ckeditor.fields.RichTextField(verbose_name='Список инградиентов'),
        ),
        migrations.AlterField(
            model_name='post',
            name='prep_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Время на подготовку'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='post', to='blog.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
