# Generated by Django 4.2.8 on 2023-12-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_category_alter_post_cook_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_to_read',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Время на чтение'),
        ),
    ]
